fix the .travis.yml script
lanl/LATTE pull request #110
Opened 2019-11-05 18:16 UTC by ares201005

2019-11-05 18:27 UTC, junghans requested changes
What is broken with C++11? Why do you need C++98?

2019-11-05 18:34 UTC, ares201005 commented
Actually, I have another modification that turns on the c++11
compatibility, i.e., use "-std=c++11 flag". use this version?

On Tue, Nov 5, 2019 at 11:27 AM Christoph Junghans <notifications@github.com>
wrote:

> *@junghans* requested changes on this pull request.
>
> What is broken with C++11? Why do you need C++98?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lanl/LATTE/pull/110?email_source=notifications&email_token=ABA34V745L6AH6B2GLU7KRTQSG3IZA5CNFSM4JJGFXSKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCKL6Z5Y#pullrequestreview-311946487>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABA34V56ZFBPSIA7CLFMOUTQSG3IZANCNFSM4JJGFXSA>
> .
>

2019-11-05 18:39 UTC, ares201005 commented on .travis.yml
> +         cd $HOME/lammps && mkdir build && cd build && cmake ../cmake -DPKG_MOLECULE=ON -DPKG_LATTE=ON -DCMAKE_PREFIX_PATH=$HOME/latte/install && sed -i "s/-DLAMMPS_SMALLBIG/-DLAMMPS_SMALLBIG -DLAMMP
Thanks for the hint. Another question, if I want to use c++11, how can I add "-std=c++11" to the "CMakeFiles/lmp.dir/flags.make" file using cmake?

2019-11-05 18:41 UTC, junghans commented on .travis.yml
> +         cd $HOME/lammps && mkdir build && cd build && cmake ../cmake -DPKG_MOLECULE=ON -DPKG_LATTE=ON -DCMAKE_PREFIX_PATH=$HOME/latte/install && sed -i "s/-DLAMMPS_SMALLBIG/-DLAMMPS_SMALLBIG -DLAMMP
`-DCMAKE_CXX_STANDARD=11` or add `-std=c++11` to CXXFLAGS.

2019-11-05 18:53 UTC, ares201005 commented on .travis.yml
> +         cd $HOME/lammps && mkdir build && cd build && cmake ../cmake -DPKG_MOLECULE=ON -DPKG_LATTE=ON -DCMAKE_PREFIX_PATH=$HOME/latte/install && sed -i "s/-DLAMMPS_SMALLBIG/-DLAMMPS_SMALLBIG -DLAMMP
Thank you! I will use the "-DCMAKE_CXX_STANDARD=11" option.

2019-11-15 21:01 UTC, cnegre approved these changes

2019-11-15 21:02 UTC, merged